### ISSUE TITLE
Example Tests fail

### ISSUE THREAD

**Issue by funmler** [spring-projects/spring-data-book#21]
Hi was trying to get the example to run and had a few failures.
`
>git clone https://github.com/SpringSource/spring-data-book.git
>cd spring-data-book
>mvn clean package

[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] Spring Data Book
[INFO] Spring Data Book - JPA
[INFO] Spring Data Book - MongoDB
[INFO] Spring Data Book - Querydsl
[INFO] Spring Data Book - Neo4J
[INFO] Spring Data Book - JDBC
[INFO] Spring Data Book - Redis
[INFO] Spring Data Book - GemFire
[INFO] Spring Data Book - REST exporter
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Spring Data Book 1.0.0.BUILD-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ spring-data-book ---
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Spring Data Book - JPA 1.0.0.BUILD-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ spring-data-book-jpa ---
[INFO] 
[INFO] --- apt-maven-plugin:1.0.8:process (default) @ spring-data-book-jpa ---
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ spring-data-book-jpa ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.0:compile (default-compile) @ spring-data-book-jpa ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 21 source files to /home/joe/dev/spring-data-book/jpa/target/classes
[WARNING] /home/joe/dev/spring-data-book/jpa/target/generated-sources/com/oreilly/springdata/jpa/core/QProduct.java: Some input files use unchecked or unsafe operations.
[WARNING] /home/joe/dev/spring-data-book/jpa/target/generated-sources/com/oreilly/springdata/jpa/core/QProduct.java: Recompile with -Xlint:unchecked for details.
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ spring-data-book-jpa ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.0:testCompile (default-testCompile) @ spring-data-book-jpa ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 9 source files to /home/joe/dev/spring-data-book/jpa/target/test-classes
[INFO] 
[INFO] --- maven-surefire-plugin:2.13:test (default-test) @ spring-data-book-jpa ---
[INFO] Surefire report directory: /home/joe/dev/spring-data-book/jpa/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.oreilly.springdata.jpa.core.ProductRepositoryIntegrationTest
2016-03-25 15:03:12,928  INFO ontext.support.GenericApplicationContext: 510 - Refreshing org.springframework.context.support.GenericApplicationContext@56aac163: startup date [Fri Mar 25 15:03:12 MDT 2016]; root of context hierarchy
2016-03-25 15:03:13,006 ERROR ramework.test.context.TestContextManager: 315 - Caught exception while allowing TestExecutionListener [org.springframework.test.context.support.DependencyInjectionTestExecutionListener@4fe767f3] to prepare test instance [com.oreilly.springdata.jpa.core.ProductRepositoryIntegrationTest@2805c96b]
java.lang.IllegalStateException: Failed to load ApplicationContext
	at org.springframework.test.context.TestContext.getApplicationContext(TestContext.java:157) ~[spring-test-3.2.1.RELEASE.jar:3.2.1.RELEASE]
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.injectDependencies(DependencyInjectionTestExecutionListener.java:109) ~[spring-test-3.2.1.RELEASE.jar:3.2.1.RELEASE]
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.prepareTestInstance(DependencyInjectionTestExecutionListener.java:75) ~[spring-test-3.2.1.RELEASE.jar:3.2.1.RELEASE]
	at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:313) ~[spring-test-3.2.1.RELEASE.jar:3.2.1.RELEASE]
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.createTest(SpringJUnit4ClassRunner.java:211) [spring-test-3.2.1.RELEASE.jar:3.2.1.RELEASE]
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner$1.runReflectiveCall(SpringJUnit4ClassRunner.java:288) [spring-test-3.2.1.RELEASE.jar:3.2.1.RELEASE]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15) [junit-dep-4.10.jar:na]
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.methodBlock(SpringJUnit4ClassRunner.java:284) [spring-test-3.2.1.RELEASE.jar:3.2.1.RELEASE]
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:231) [spring-test-3.2.1.RELEASE.jar:3.2.1.RELEASE]
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:88) [spring-test-3.2.1.RELEASE.jar:3.2.1.RELEASE]
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231) [junit-dep-4.10.jar:na]
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60) [junit-dep-4.10.jar:na]
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229) [junit-dep-4.10.jar:na]
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50) [junit-dep-4.10.jar:na]
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222) [junit-dep-4.10.jar:na]
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61) [spring-test-3.2.1.RELEASE.jar:3.2.1.RELEASE]
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:71) [spring-test-3.2.1.RELEASE.jar:3.2.1.RELEASE]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300) [junit-dep-4.10.jar:na]
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:174) [spring-test-3.2.1.RELEASE.jar:3.2.1.RELEASE]
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264) [surefire-junit4-2.13.jar:2.13]
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153) [surefire-junit4-2.13.jar:2.13]
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124) [surefire-junit4-2.13.jar:2.13]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_74]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_74]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_74]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_74]
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray2(ReflectionUtils.java:208) [surefire-api-2.13.jar:2.13]
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:158) [surefire-booter-2.13.jar:2.13]
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:86) [surefire-booter-2.13.jar:2.13]
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153) [surefire-booter-2.13.jar:2.13]
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:95) [surefire-booter-2.13.jar:2.13]
Caused by: java.lang.IllegalArgumentException: null
	at org.springframework.asm.ClassReader.<init>(Unknown Source) ~[spring-core-3.2.1.RELEASE.jar:3.2.1.RELEASE]
	at org.springframework.asm.ClassReader.<init>(Unknown Source) ~[spring-core-3.2.1.RELEASE.jar:3.2.1.RELEASE]
	at org.springframework.asm.ClassReader.<init>(Unknown Source) ~[spring-core-3.2.1.RELEASE.jar:3.2.1.RELEASE]
<snip>
Results :

Tests in error: 
   » IllegalState Failed to load ApplicationContext
   » IllegalState Failed to load ApplicationContext
   » IllegalState Failed to load ApplicationContext
   » IllegalState Failed to load ApplicationContext
   » IllegalState Failed to load ApplicationContext
   » IllegalState Failed to load ApplicationContext
   » IllegalState Failed to load ApplicationContext
   » IllegalState Failed to load ApplicationContext
   » IllegalState Failed to load ApplicationContext
  ApplicationConfigTest.bootstrapAppFromJavaConfig:38 » IllegalArgument
  ApplicationConfigTest.bootstrapAppFromXml:46 » BeanDefinitionParsing Configura...
   » IllegalState Failed to load ApplicationContext
   » IllegalState Failed to load ApplicationContext

Tests run: 13, Failures: 0, Errors: 13, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Spring Data Book ................................... SUCCESS [  0.139 s]
[INFO] Spring Data Book - JPA ............................. FAILURE [  3.349 s]
[INFO] Spring Data Book - MongoDB ......................... SKIPPED
[INFO] Spring Data Book - Querydsl ........................ SKIPPED
[INFO] Spring Data Book - Neo4J ........................... SKIPPED
[INFO] Spring Data Book - JDBC ............................ SKIPPED
[INFO] Spring Data Book - Redis ........................... SKIPPED
[INFO] Spring Data Book - GemFire ......................... SKIPPED
[INFO] Spring Data Book - REST exporter ................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.647 s
[INFO] Finished at: 2016-03-25T15:03:13-06:00
[INFO] Final Memory: 23M/283M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.13:test (default-test) on project spring-data-book-jpa: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/joe/dev/spring-data-book/jpa/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :spring-data-book-jpa
`

**Comment by JannoTilk** [comment]
I have got exactly the same problem. Has anyone found solution?
IntelliJ 15.0.3 Win 10 Pro

**Comment by faissalwise** [comment]
It's just a compilation problem,we must compile your project with the JDK 6.So make sure we use the appropriate compiler version.

**Comment by acohen1644** [comment]
I'm using a system whose security constraints make it difficult for me to install another JDK. Is there some way to make this work with JDK 8?

**Comment by pogoretska** [comment]
Tests are failing; when skipping them, got an

[ERROR] Failed to execute goal on project spring-data-book-neo4j: Could not resolve dependencies for project com.oreilly.springdata:spring-data-book-neo4j:jar:1.0.0.BUILD-SNAPSHOT: Could not find artifact org.neo4j:neo4j-cypher-dsl:jar:1.8 in neo4j-public-release-repository (http://m2.neo4j.org/releases) -> [Help 1]

**Comment by VonUniGE** [comment]
Last commit is from 9 Apr 2013. Is this project still officially supported?
